language: node_js
sudo: false

node_js:
  - "10"

git:
  depth: false

env:
  - WSGNATSD_VERSION=v0.6.1

before_script:
  - wget "https://github.com/aricart/wsgnatsd/releases/download/$WSGNATSD_VERSION/wsgnatsd-$WSGNATSD_VERSION-linux-amd64.zip" -O tmp.zip
  - unzip -d wsgnatsd tmp.zip

script:
  - npm run test
#  - npm run coveralls