language: node_js
sudo: false

node_js:
- "10"

git:
  depth: false

env:
  global:
  - WSGNATSD_VERSION=v0.7.3
  - NODE_EXTRA_CA_CERTS=$TRAVIS_BUILD_DIR/test/helpers/certs/ca.pem

before_script:
- wget "https://github.com/aricart/wsgnatsd/releases/download/$WSGNATSD_VERSION/wsgnatsd-$WSGNATSD_VERSION-linux-amd64.zip" -O tmp.zip
- unzip -d wsgnatsd tmp.zip

script:
- npm run test
#  - npm run coveralls